### ISSUE TITLE
Regarding Solutions in Java

### ISSUE THREAD

**Issue by ATRI2107** [aman-nidhi/DSA-Solutions#8]
@aman-nidhi I would like to provide some DSA codes in Leetcode directory in Java. Since there are many who code in Java so it will be better for them.

**Comment by aman-nidhi** [comment]
Thank you @ATRI2107 for the PR. Yes, it would be helpful for the java programmers and it is very thoughtful of you.

**Comment by ATRI2107** [comment]
@aman-nidhi you're welcome 😁
